<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.WebView" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIQuester.ViewModel\SIQuester.ViewModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\..\..\deploy\SIQuester.Bootstrapper\Resources\logo.png" Link="Assets\logo.png" />
  </ItemGroup>
</Project>
