using System.Globalization;
using System.Resources;

namespace SIQuester.Avalonia.Localization;

/// <summary>
/// Provides localized strings for the Avalonia frontend. Language changes apply after restart.
/// </summary>
public static class UiStrings
{
    private static readonly ResourceManager ResourceManager = new(
        "SIQuester.Avalonia.Localization.UiResources",
        typeof(UiStrings).Assembly);

    public static string Get(string name) => ResourceManager.GetString(name, CultureInfo.CurrentUICulture)
        ?? throw new MissingManifestResourceException($"Missing UI resource: {name}");

    public static string AppTitle => Get(nameof(AppTitle));
    public static string New => Get(nameof(New));
    public static string Open => Get(nameof(Open));
    public static string Save => Get(nameof(Save));
    public static string SaveAs => Get(nameof(SaveAs));
    public static string Undo => Get(nameof(Undo));
    public static string Redo => Get(nameof(Redo));
    public static string Close => Get(nameof(Close));
    public static string Cut => Get(nameof(Cut));
    public static string Copy => Get(nameof(Copy));
    public static string Paste => Get(nameof(Paste));
    public static string RecentFiles => Get(nameof(RecentFiles));
    public static string Exit => Get(nameof(Exit));
    public static string Create => Get(nameof(Create));
    public static string Cancel => Get(nameof(Cancel));
    public static string Discard => Get(nameof(Discard));
    public static string Yes => Get(nameof(Yes));
    public static string No => Get(nameof(No));
    public static string OK => Get(nameof(OK));
    public static string File => Get(nameof(File));
    public static string Edit => Get(nameof(Edit));
    public static string View => Get(nameof(View));
    public static string Navigator => Get(nameof(Navigator));
    public static string Editor => Get(nameof(Editor));
    public static string Inspector => Get(nameof(Inspector));
    public static string Media => Get(nameof(Media));
    public static string StatusReady => Get(nameof(StatusReady));
    public static string EmptyTitle => Get(nameof(EmptyTitle));
    public static string EmptyDescription => Get(nameof(EmptyDescription));
    public static string PackageName => Get(nameof(PackageName));
    public static string PackageAuthor => Get(nameof(PackageAuthor));
    public static string Template => Get(nameof(Template));
    public static string QualityControl => Get(nameof(QualityControl));
    public static string Name => Get(nameof(Name));
    public static string Package => Get(nameof(Package));
    public static string Round => Get(nameof(Round));
    public static string Theme => Get(nameof(Theme));
    public static string Question => Get(nameof(Question));
    public static string QuestionText => Get(nameof(QuestionText));
    public static string Price => Get(nameof(Price));
    public static string RightAnswers => Get(nameof(RightAnswers));
    public static string WrongAnswers => Get(nameof(WrongAnswers));
    public static string Comments => Get(nameof(Comments));
    public static string Metadata => Get(nameof(Metadata));
    public static string Authors => Get(nameof(Authors));
    public static string Sources => Get(nameof(Sources));
    public static string Tags => Get(nameof(Tags));
    public static string ShowmanComments => Get(nameof(ShowmanComments));
    public static string SelectedEntry => Get(nameof(SelectedEntry));
    public static string Add => Get(nameof(Add));
    public static string MoveUp => Get(nameof(MoveUp));
    public static string MoveDown => Get(nameof(MoveDown));
    public static string AddRound => Get(nameof(AddRound));
    public static string AddTheme => Get(nameof(AddTheme));
    public static string AddQuestion => Get(nameof(AddQuestion));
    public static string Delete => Get(nameof(Delete));
    public static string Images => Get(nameof(Images));
    public static string Audio => Get(nameof(Audio));
    public static string Video => Get(nameof(Video));
    public static string Html => Get(nameof(Html));
    public static string NoSelection => Get(nameof(NoSelection));
    public static string Saving => Get(nameof(Saving));
    public static string Loading => Get(nameof(Loading));
    public static string Options => Get(nameof(Options));
    public static string ThemeMode => Get(nameof(ThemeMode));
    public static string ThemeSystem => Get(nameof(ThemeSystem));
    public static string ThemeLight => Get(nameof(ThemeLight));
    public static string ThemeDark => Get(nameof(ThemeDark));
    public static string Language => Get(nameof(Language));
    public static string LanguageRestart => Get(nameof(LanguageRestart));
    public static string SettingsSavingError => Get(nameof(SettingsSavingError));
    public static string Reset => Get(nameof(Reset));
    public static string RecoveryTitle => Get(nameof(RecoveryTitle));
    public static string RecoveryDescription => Get(nameof(RecoveryDescription));
    public static string RecoveryAvailable => Get(nameof(RecoveryAvailable));
    public static string RecoveryStale => Get(nameof(RecoveryStale));
    public static string RecoveryStaleDescription => Get(nameof(RecoveryStaleDescription));
    public static string RecoveryOriginalPath => Get(nameof(RecoveryOriginalPath));
    public static string RecoveryUnsavedDocument => Get(nameof(RecoveryUnsavedDocument));
    public static string RecoverySavedAt => Get(nameof(RecoverySavedAt));
    public static string RecoverySizeBytes => Get(nameof(RecoverySizeBytes));
    public static string Preview => Get(nameof(Preview));
    public static string Restore => Get(nameof(Restore));
    public static string RestoreAsCopy => Get(nameof(RestoreAsCopy));
    public static string RevealLocation => Get(nameof(RevealLocation));
    public static string DiscardSnapshot => Get(nameof(DiscardSnapshot));
    public static string ConfirmDiscardSnapshot => Get(nameof(ConfirmDiscardSnapshot));
    public static string RecoveryPreview => Get(nameof(RecoveryPreview));
    public static string Rounds => Get(nameof(Rounds));
    public static string Themes => Get(nameof(Themes));
    public static string Questions => Get(nameof(Questions));
    public static string MediaFiles => Get(nameof(MediaFiles));
    public static string Scenario => Get(nameof(Scenario));
    public static string ContentItems => Get(nameof(ContentItems));
    public static string ContentValue => Get(nameof(ContentValue));
    public static string Placement => Get(nameof(Placement));
    public static string DurationSeconds => Get(nameof(DurationSeconds));
    public static string WaitForFinish => Get(nameof(WaitForFinish));
    public static string PackageMediaReference => Get(nameof(PackageMediaReference));
    public static string AddScreenText => Get(nameof(AddScreenText));
    public static string AddReplicText => Get(nameof(AddReplicText));
    public static string ParameterReference => Get(nameof(ParameterReference));
    public static string Minimum => Get(nameof(Minimum));
    public static string Maximum => Get(nameof(Maximum));
    public static string Step => Get(nameof(Step));
    public static string StepType => Get(nameof(StepType));
    public static string AnswerType => Get(nameof(AnswerType));
    public static string TextAnswer => Get(nameof(TextAnswer));
    public static string NumberAnswer => Get(nameof(NumberAnswer));
    public static string PointAnswer => Get(nameof(PointAnswer));
    public static string SelectAnswer => Get(nameof(SelectAnswer));
    public static string ClientManagedAnswer => Get(nameof(ClientManagedAnswer));
    public static string ClientManagedDescription => Get(nameof(ClientManagedDescription));
    public static string NumericAnswer => Get(nameof(NumericAnswer));
    public static string AnswerDeviation => Get(nameof(AnswerDeviation));
    public static string PointCoordinates => Get(nameof(PointCoordinates));
    public static string AnswerOptions => Get(nameof(AnswerOptions));
    public static string RightOption => Get(nameof(RightOption));
    public static string MarkRightAnswer => Get(nameof(MarkRightAnswer));
    public static string AddOption => Get(nameof(AddOption));
    public static string AddStep => Get(nameof(AddStep));
    public static string ParameterName => Get(nameof(ParameterName));
    public static string AddSimpleParameter => Get(nameof(AddSimpleParameter));
    public static string AddContentParameter => Get(nameof(AddContentParameter));
    public static string AddGroupParameter => Get(nameof(AddGroupParameter));
    public static string AddNumberSetParameter => Get(nameof(AddNumberSetParameter));
    public static string AddReferenceParameter => Get(nameof(AddReferenceParameter));
    public static string SelectPoint => Get(nameof(SelectPoint));
    public static string LoadingImage => Get(nameof(LoadingImage));
    public static string ImageUnavailable => Get(nameof(ImageUnavailable));
    public static string Publisher => Get(nameof(Publisher));
    public static string ContactAddress => Get(nameof(ContactAddress));
    public static string CreationDate => Get(nameof(CreationDate));
    public static string PackageLanguage => Get(nameof(PackageLanguage));
    public static string Restriction => Get(nameof(Restriction));
    public static string Difficulty => Get(nameof(Difficulty));
    public static string RoundType => Get(nameof(RoundType));
    public static string StandardRound => Get(nameof(StandardRound));
    public static string FinalRound => Get(nameof(FinalRound));
}
